(()=>{'use strict';
const C=globalThis.MAGASIN_CORE;if(!C)return;const host=()=>document.getElementById('employeeApp'),d=()=>host()?.contentDocument||null,esc=C.security.escapeHtml,hm=C.time.time5;
let state={week:C.date.addDays(C.date.monday(),7),rows:[],stores:[]};
const STORE_CODES=['CN1','CN2','CN3','CN4'],DAY_NAMES=['Thứ Hai','Thứ Ba','Thứ Tư','Thứ Năm','Thứ Sáu','Thứ Bảy','Chủ Nhật'];
const options=sel=>{let s='';for(let m=0;m<1440;m+=30){const v=`${String(Math.floor(m/60)).padStart(2,'0')}:${String(m%60).padStart(2,'0')}`;s+=`<option value="${v}"${v===hm(sel)?' selected':''}>${v}</option>`}return s};
function open(){const x=d();if(!x)return;const p=x.getElementById('weeklyRegistrationPanel');if(p)p.classList.add('open');prepare(x)}
function close(){const x=d();const p=x?.getElementById('weeklyRegistrationPanel');if(p)p.classList.remove('open')}
async function prepare(x){if(!x)return;const st=x.getElementById('quickRegStart'),en=x.getElementById('quickRegEnd');if(st&&!st.dataset.engineBound){st.innerHTML=options('06:00');st.dataset.engineBound='1'}if(en&&!en.dataset.engineBound){en.innerHTML=options('12:00');en.dataset.engineBound='1'}const day=x.getElementById('quickRegDay');if(day&&!day.dataset.engineBound){day.innerHTML=C.date.weekDays(state.week).map((k,i)=>`<option value="${k}">${DAY_NAMES[i]} · ${C.date.formatDate(k)}</option>`).join('');day.dataset.engineBound='1'}if(!state.stores.length)state.stores=await C.stores.active().catch(()=>[]);const select=x.getElementById('quickRegStore');if(select&&!select.dataset.engineBound){const stores=state.stores.length?state.stores:STORE_CODES.map(code=>({code}));select.innerHTML=stores.map(s=>`<option value="${esc(s.code)}">${esc(s.code)}${s.name?` · ${esc(s.name)}`:''}</option>`).join('');select.dataset.engineBound='1'}await load()}
async function load(){const x=d();if(!x)return;const q=await C.supabase.rpc('get_my_availability',{p_week_start:state.week});if(q.error){C.ui.toast('Không tải được đăng ký lịch: '+q.error.message,'error');return}state.rows=Array.isArray(q.data)?q.data:[];renderSummary()}
function renderSummary(){const x=d();if(!x)return;const box=x.querySelector('#weeklyRegistrationPanel .week-summary');if(!box)return;const days=C.date.weekDays(state.week);const storeName=id=>state.stores.find(s=>String(s.id)===String(id))?.code||state.stores.find(s=>String(s.id)===String(id))?.name||'Chi nhánh';box.innerHTML=days.map((k,i)=>{const rows=state.rows.filter(r=>String(r.work_date).slice(0,10)===k).sort((a,b)=>C.time.minutes(a.start_time)-C.time.minutes(b.start_time));return `<div class="mini"><h4>${DAY_NAMES[i]}</h4><div class="date">${C.date.formatDate(k)}</div>${rows.length?rows.map(r=>`<div class="miniShift"><b>${esc(hm(r.start_time))}–${esc(hm(r.end_time))}</b><br>${esc(storeName(r.preferred_store_id))}<br><span>Đã đăng ký</span>${r.id?`<br><button type="button" data-av-delete="${esc(r.id)}" style="margin-top:6px;border:1px solid #e2b5b0;background:#fff;color:#9d3f30;border-radius:7px;padding:4px 7px;font:inherit;cursor:pointer">Xóa</button>`:''}</div>`).join(''):'<div class="muted" style="margin-top:17px">Chưa đăng ký</div>'}</div>`}).join('');box.querySelectorAll('[data-av-delete]').forEach(b=>b.addEventListener('click',()=>remove(b.dataset.avDelete,b)))}
async function register(){const x=d();if(!x)return;const day=x.getElementById('quickRegDay')?.value,start=x.getElementById('quickRegStart')?.value,end=x.getElementById('quickRegEnd')?.value,store=x.getElementById('quickRegStore')?.value,msg=x.getElementById('quickRegMsg');if(!day||!start||!end)return;if(C.time.minutes(end)<=C.time.minutes(start)){if(msg)msg.textContent='Giờ kết thúc phải sau giờ bắt đầu.';return}if(!state.stores.length)state.stores=await C.stores.active().catch(()=>[]);const target=state.stores.find(s=>String(s.code)===String(store));if(!target){if(msg)msg.textContent='Không tìm thấy chi nhánh.';return}const q=await C.supabase.rpc('save_my_availability',{p_availability_id:null,p_work_date:day,p_start_time:start,p_end_time:end,p_availability_type:'AVAILABLE',p_preferred_store_id:target.id,p_note:null});if(q.error){if(msg)msg.textContent='Đăng ký thất bại: '+q.error.message;return}if(msg)msg.textContent='Đã đăng ký lịch làm.';C.ui.toast('Đã lưu đăng ký lịch làm.','success');await load()}
async function remove(id,button){const x=d();if(!x||!id)return;const msg=x.getElementById('quickRegMsg');if(!confirm('Xóa khoảng thời gian đã đăng ký này?'))return;if(button)button.disabled=true;try{const q=await C.supabase.rpc('delete_my_availability',{p_availability_id:id});if(q.error)throw q.error;if(q.data!==true)throw new Error('DELETE_NOT_CONFIRMED');if(msg)msg.textContent='Đã xóa khoảng thời gian.';C.ui.toast('Đã xóa khoảng thời gian đăng ký.','success');await load()}catch(e){if(msg)msg.textContent='Xóa thất bại: '+(e.message||e);C.ui.toast('Không thể xóa đăng ký lịch.','error')}finally{if(button&&button.isConnected)button.disabled=false}}
async function finish(){const msg=d()?.getElementById('quickRegMsg');if(msg)msg.textContent='Đã hoàn thành đăng ký lịch làm.';C.ui.toast('Đã hoàn thành đăng ký lịch.','success')}
function wire(x,selector,fn){const b=x.querySelector(selector);if(!b||b.dataset.engineBound)return;b.removeAttribute('onclick');b.dataset.engineBound='1';b.addEventListener('click',fn)}
function bind(){const x=d();if(!x||x.body.dataset.employeeAvailabilityEngine==='1')return;x.body.dataset.employeeAvailabilityEngine='1';wire(x,'[onclick="openWeeklyRegistration()"]',open);wire(x,'#weeklyRegistrationPanel button[onclick="closeWeeklyRegistration()"]',close);wire(x,'#weeklyRegistrationPanel button[onclick="quickRegister()"]',register);wire(x,'#weeklyRegistrationPanel button[onclick="finishQuickRegistration()"]',finish)}
function init(){const f=host();if(!f||f.dataset.availabilityEngine==='1')return;f.dataset.availabilityEngine='1';f.addEventListener('load',()=>{bind();prepare(f.contentDocument)},{once:false});if(f.contentDocument){bind();prepare(f.contentDocument)}}
globalThis.MAGASIN_EMPLOYEE=globalThis.MAGASIN_EMPLOYEE||{};globalThis.MAGASIN_EMPLOYEE.availability={refresh:load,open,close,remove,getRows:()=>state.rows.slice(),getWeek:()=>state.week};if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
})();