(()=>{'use strict';
const C=globalThis.MAGASIN_CORE;if(!C)return;const host=()=>document.getElementById('employeeApp'),d=()=>host()?.contentDocument||null,esc=C.security.escapeHtml,hm=C.time.time5,fmt=C.date.formatDate;
let mode='swap',state={my:[],candidates:[],history:[]};
function myShiftOptions(){return state.my.map(r=>`<option value="${esc(r.schedule_id||'')}">${esc(fmt(r.work_date))} · ${esc(hm(r.start_time))}–${esc(hm(r.end_time))} · ${esc(r.store_code||r.store_name||'')}</option>`).join('')}
function panel(){return d()?.getElementById('view-swap')}
async function loadMy(){const q=await C.supabase.rpc('list_my_approved_schedules_v2',{p_week_start:C.date.monday()});if(q.error){C.ui.toast('Không tải được ca để đổi: '+q.error.message,'error');return}state.my=Array.isArray(q.data)?q.data:[];const x=panel();const card=x?.querySelector('.swap-card');if(card){const f=[...card.querySelectorAll('.field')];const old=card.querySelector('.employeeSwapSchedule');if(old)old.remove();const wrap=x.createElement('div');wrap.className='field employeeSwapSchedule';wrap.innerHTML=`<label>Ca của tôi</label><select id="employeeRequesterSchedule">${myShiftOptions()}</select>`;card.insertBefore(wrap, f[0]||null)}await loadCandidates();await loadHistory()}
async function loadCandidates(){const x=panel(),sel=x?.querySelector('#employeeRequesterSchedule');if(!sel)return;const q=await C.supabase.rpc('list_shift_swap_candidates_v1',{p_requester_schedule_id:sel.value||null});if(q.error){C.ui.toast('Không tải được nhân viên/ca đối ứng: '+q.error.message,'error');return}state.candidates=Array.isArray(q.data)?q.data:[];const box=x.querySelector('#employeeSwapTarget');if(box)box.innerHTML=state.candidates.map(r=>`<option value="${esc(r.schedule_id)}">${esc(r.user_name)} · ${esc(fmt(r.work_date))} · ${esc(hm(r.start_time))}–${esc(hm(r.end_time))}</option>`).join('')||'<option value="">Không có ca phù hợp</option>'}
async function submit(){const x=panel(),req=x?.querySelector('#employeeRequesterSchedule'),target=x?.querySelector('#employeeSwapTarget'),reason=x?.querySelector('#employeeSwapReason');if(!req?.value||!target?.value)return show('Vui lòng chọn ca của bạn và ca muốn đổi.');const q=await C.supabase.rpc('submit_shift_swap_request',{p_requester_schedule_id:req.value,p_target_schedule_id:target.value,p_reason:reason?.value||''});if(q.error)return show('Gửi yêu cầu thất bại: '+q.error.message);show('Đã gửi yêu cầu đổi ca.');C.ui.toast('Đã gửi yêu cầu đổi ca.','success');await loadHistory()}
async function loadHistory(){const q=await C.supabase.rpc('list_my_shift_swaps_v2');if(q.error)return;state.history=Array.isArray(q.data)?q.data:[];const x=panel(),box=x?.querySelector('#historyList');if(!box)return;box.innerHTML=state.history.length?state.history.map(r=>`<div class="history-item"><div><b>${esc(fmt(r.requester_date))} · ${esc(hm(r.requester_start))}–${esc(hm(r.requester_end))} · ${esc(r.store_code||'')}</b><div class="muted">${esc(r.target_user_name||'')} · ${esc(r.target_date?fmt(r.target_date):'')}</div></div><span class="badge ${String(r.status).toUpperCase()==='APPROVED'?'green':String(r.status).toUpperCase()==='REJECTED'?'red':'amber'}">${esc(r.status||'PENDING')}</span></div>`).join(''):'<div class="empty">Chưa có yêu cầu đổi ca.</div>'}
function show(t){const x=panel(),e=x?.querySelector('#swapResult');if(e){e.textContent=t;e.classList.add('open')}}
function configure(x){if(!x||x.dataset.employeeSwapEngine==='1')return;x.dataset.employeeSwapEngine='1';x.querySelectorAll('[onclick^="openSwapForm"]').forEach(b=>{const old=b.getAttribute('onclick');b.removeAttribute('onclick');b.addEventListener('click',()=>{mode=old.includes("'give'")?'give':'swap';openForm()})});x.querySelectorAll('[onclick="backToSwapChoices()"]') .forEach(b=>{b.removeAttribute('onclick');b.addEventListener('click',back)});x.querySelector('[onclick="sendSwapRequest()"]')?.removeAttribute('onclick');x.querySelector('#swapForm .swap-actions .btn.primary')?.addEventListener('click',submit);x.querySelector('[onclick="sendSwapRequest()"]')?.addEventListener('click',submit);x.querySelector('#employeeRequesterSchedule')?.addEventListener('change',loadCandidates)}
function openForm(){const x=panel();if(!x)return;x.querySelector('#swapChoices')?.setAttribute('style','display:none');x.querySelector('#swapForm')?.classList.add('open');const extra=x.querySelector('#swapExtra'),hint=x.querySelector('#giveOnlyHint');if(mode==='give'){if(extra)extra.style.display='none';if(hint)hint.style.display='block'}else{if(extra)extra.style.display='block';if(hint)hint.style.display='none'}loadMy()}
function back(){const x=panel();if(!x)return;x.querySelector('#swapChoices')?.setAttribute('style','');x.querySelector('#swapForm')?.classList.remove('open')}
function renderForm(){const x=panel();if(!x)return;const card=x.querySelector('.swap-card:nth-child(2)');if(!card)return;const fields=card.querySelector('.field');if(fields&&!x.getElementById('employeeSwapTarget')){const wrap=x.createElement('div');wrap.className='field';wrap.innerHTML='<label>Ca đối ứng</label><select id="employeeSwapTarget"><option value="">Chọn ca</option></select>';card.insertBefore(wrap,fields.nextSibling||null)}if(!x.getElementById('employeeSwapReason')){const wrap=x.createElement('div');wrap.className='field';wrap.innerHTML='<label>Lý do</label><input id="employeeSwapReason" type="text" placeholder="Lý do (không bắt buộc)">';card.appendChild(wrap)}configure(x)}
function init(){const f=host();if(!f||f.dataset.swapEngine==='1')return;f.dataset.swapEngine='1';f.addEventListener('load',()=>{renderForm();loadHistory()});if(f.contentDocument){renderForm();loadHistory()}}
globalThis.MAGASIN_EMPLOYEE=globalThis.MAGASIN_EMPLOYEE||{};globalThis.MAGASIN_EMPLOYEE.swap={refresh:()=>{renderForm();loadMy();loadHistory()}};if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
})();