function humanQty(value,unit){const n=Number(value||0);if(!Number.isFinite(n))return '—';if(unit==='g'&&Math.abs(n)>=1000)return `${number(n/1000)} kg`;if(unit==='ml'&&Math.abs(n)>=1000)return `${number(n/1000)} lít`;return `${number(n)} ${unit||''}`.trim()}
function referenceText(c,p){if(!c?.source_price||!c?.reference_base_quantity)return 'Chưa có giá tham khảo';return `Giá tham khảo: ${money(c.source_price)} / ${humanQty(c.reference_base_quantity,p?.base_unit||c.base_unit)}`}
function packageOptions(productId,selected=''){const p=state.products.find(x=>x.id===productId),c=ctx(productId),packs=state.packages.filter(x=>x.product_id===productId&&x.status==='ACTIVE');let html='';if(c?.source_price!=null&&Number(c.reference_base_quantity)>0)html+=`<option value="${sourceModeValue()}" ${selected===sourceModeValue()?'selected':''}>Giá tham khảo · ${esc(humanQty(c.reference_base_quantity,p?.base_unit||''))}</option>`;html+=`<option value="" ${selected||c?.source_price!=null?'':'selected'}>${p?`Đơn vị chuẩn · ${esc(p.base_unit)}`:'Đơn vị chuẩn'}</option>`;for(const x of packs)html+=`<option value="${x.id}" ${selected===x.id?'selected':''}>${esc(x.label)} · ${esc(humanQty(x.base_qty_per_unit,p?.base_unit||''))}</option>`;return html}
function productOptions(selected=''){const term=($('#lineProductFilter').value||'').trim().toLowerCase(),active=state.products.filter(p=>p.status==='ACTIVE'&&(!term||`${p.code} ${p.name}`.toLowerCase().includes(term)));return '<option value="">-- Chọn hàng hóa --</option>'+active.map(p=>`<option value="${p.id}" ${p.id===selected?'selected':''}>${esc(p.name)} · ${esc(p.code)}</option>`).join('')}
function selectedMode(row){const productId=row.querySelector('.line-product').value,p=state.products.find(x=>x.id===productId),mode=row.querySelector('.line-package').value,c=ctx(productId);if(!p)return {factor:1,unit:'',reference:false};if(mode===sourceModeValue()&&c)return {factor:Number(c.reference_base_quantity||1),unit:'mức tham khảo',reference:true,referencePrice:Number(c.source_price||0)};const pack=state.packages.find(x=>x.id===mode);if(pack)return {factor:Number(pack.base_qty_per_unit||1),unit:pack.purchase_unit||pack.label,reference:false,package:pack};if(row.dataset.customFactor&&row.dataset.customUnit)return {factor:Number(row.dataset.customFactor),unit:row.dataset.customUnit,reference:false};return {factor:1,unit:p.base_unit,reference:false}}
function updateReferenceCoverage(){const covered=state.products.filter(p=>ctx(p.id)?.source_price!=null).length,el=$('#referenceCoverage');if(!el)return;el.className='notice '+(state.priceReferenceAvailable?'info':'warn');el.innerHTML=state.priceReferenceAvailable?`Có <strong>${covered}/${state.products.length}</strong> mặt hàng có giá và quy cách tham khảo. Mặt hàng còn lại nhập theo hóa đơn thực tế.`:'Chưa tải được bảng giá tham khảo; vẫn có thể nhập đơn theo hóa đơn thực tế.'}
function renderProducts(){const body=$('#productsBody');if(!body)return;body.innerHTML='';for(const p of filteredProducts()){const packs=state.packages.filter(x=>x.product_id===p.id&&x.status==='ACTIVE'),c=ctx(p.id),ref=c?.source_price!=null?`<strong>${money(c.source_price)}</strong><div class="hint">${esc(humanQty(c.reference_base_quantity,p.base_unit))} / mức tham khảo</div>`:'<span class="badge warn">Chưa có giá tham khảo</span>',tr=document.createElement('tr');tr.innerHTML=`<td><strong>${esc(p.code)}</strong></td><td>${esc(p.name)}</td><td>${esc(catLabel[p.category]||p.category)}</td><td><span class="badge ${p.base_unit==='cái'?'':'blue'}">${esc(p.base_unit)}</span></td><td>${ref}</td><td>${packs.length?packs.map(x=>`${esc(x.label)} = ${esc(humanQty(x.base_qty_per_unit,p.base_unit))}`).join('<br>'):'<span class="muted">Chưa có quy cách riêng</span>'}</td><td>${p.status==='ACTIVE'?'<span class="badge ok">Đang dùng</span>':'<span class="badge">Ngưng dùng</span>'}</td><td><button class="btn small" data-edit-product="${p.id}">Sửa</button></td>`;body.appendChild(tr)}$('#productsEmpty').classList.toggle('hidden',body.children.length>0)}
function syncLineDefaults(row,{fromExisting=false,item={}}={}){const productId=row.querySelector('.line-product').value,p=state.products.find(x=>x.id===productId),c=ctx(productId),pkg=row.querySelector('.line-package');row.querySelector('.line-reference').textContent=p?referenceText(c,p):'';if(!p){pkg.innerHTML='<option value="">-- Chọn quy cách --</option>';updateLine(row);return}if(!fromExisting){pkg.innerHTML=packageOptions(productId,c?.source_price!=null?sourceModeValue():'');delete row.dataset.customFactor;delete row.dataset.customUnit;if(c?.source_price!=null){row.querySelector('.line-qty').value='1';row.querySelector('.line-price').value=String(Number(c.source_price))}else row.querySelector('.line-price').value=''}else if(item.package_id)pkg.value=item.package_id;else if(item.purchase_unit&&item.base_qty_per_unit){pkg.value='';row.dataset.customUnit=item.purchase_unit;row.dataset.customFactor=String(item.base_qty_per_unit)}updateLine(row)}
function priceDifferenceLabel(delta){const pct=Math.abs(Math.round(delta*100));if(pct>=500)return 'Chênh lệch rất lớn';if(Math.abs(delta)<=.1)return 'Khớp giá tham khảo';return delta>0?`Cao hơn ${pct}%`:`Thấp hơn ${pct}%`}
function updateLine(row){const productId=row.querySelector('.line-product').value,p=state.products.find(x=>x.id===productId),c=ctx(productId),qty=Number(row.querySelector('.line-qty').value||0),price=Number(row.querySelector('.line-price').value||0),mode=selectedMode(row),baseQty=qty*mode.factor,total=qty*price;row.querySelector('.line-total').textContent=money(total);row.querySelector('.line-base').textContent=p?humanQty(baseQty,p.base_unit):'—';const status=row.querySelector('.line-price-status');status.className='line-price-status';status.textContent='';if(p&&c?.source_price!=null&&qty>0){const comparable=mode.reference?Number(c.source_price):pricePerBase(c)*mode.factor;if(comparable>0&&price>=0){const delta=(price-comparable)/comparable;status.classList.add(Math.abs(delta)<=.1?'ok':Math.abs(delta)<=.25?'warn':'danger');status.textContent=priceDifferenceLabel(delta)}}updateGrandTotal()}
function polishStaticCopy(){const set=(sel,text)=>{const el=$(sel);if(el)el.textContent=text};set('.brand small','Mua hàng · công nợ · giá mua tham khảo');set('#sec-orders .section-head p','Nhập theo quy cách thực tế; hệ thống tự quy đổi về đơn vị kho và hỗ trợ đối chiếu giá mua.');set('.unit-policy .unit-chip:nth-child(1)','Nguyên liệu định lượng: g / ml');set('.unit-policy .unit-chip:nth-child(2)','Bao bì đếm chiếc: dùng “cái” khi chưa có hệ số quy đổi');set('#sec-products .section-head p','Đơn vị tồn chuẩn ưu tiên g/ml; hàng đếm chiếc chỉ giữ “cái” khi chưa có hệ số quy đổi đáng tin cậy.');const productPriceHead=$('#sec-products .data-table thead th:nth-child(5)');if(productPriceHead)productPriceHead.textContent='Giá tham khảo';set('#unitPolicyNotice','Nguyên liệu định lượng dùng g hoặc ml. Chỉ dùng “cái” cho hàng đếm chiếc khi chưa có hệ số quy đổi khối lượng hoặc thể tích.');const orderHint=$('#orderDialog .modal-head .hint');if(orderHint)orderHint.textContent='Giá tham khảo chỉ để đối chiếu. Kế toán luôn nhập đúng giá trên hóa đơn thực tế.';const help=$('#orderDialog .order-help p');if(help)help.textContent='Chọn hàng hóa → hệ thống đề xuất quy cách và giá tham khảo → điều chỉnh theo hóa đơn thực tế. Lượng nhập được tự quy đổi về đơn vị kho.';set('#orderDialog .line-tools label','Tìm nhanh hàng hóa');set('#orderDialog .line-head span:nth-child(1)','Hàng hóa');set('#orderDialog .line-head span:nth-child(2)','Quy cách mua');set('#orderDialog .line-head span:nth-child(3)','Số lượng');set('#orderDialog .line-head span:nth-child(4)','Giá hóa đơn');set('#orderDialog .line-head span:nth-child(5)','Quy đổi kho');set('#orderDialog .line-head span:nth-child(6)','Tạm tính');set('#orderDialog .sum-card:nth-child(1) small','Số mặt hàng');set('#orderDialog .sum-card:nth-child(2) small','Dòng có giá tham khảo');set('#orderDialog .sum-card:nth-child(3) small','Chênh lệch giá');set('#orderDialog .grand small','Tổng tiền nhập');const walker=document.createTreeWalker(document.body,NodeFilter.SHOW_TEXT);let node;while((node=walker.nextNode()))if(node.nodeValue?.includes('*ĐỊNH GIÁ'))node.nodeValue=node.nodeValue.replaceAll('*ĐỊNH GIÁ','bảng giá tham khảo');document.querySelectorAll('[placeholder],[title],[aria-label]').forEach(el=>{for(const a of ['placeholder','title','aria-label']){const v=el.getAttribute(a);if(v?.includes('*ĐỊNH GIÁ'))el.setAttribute(a,v.replaceAll('*ĐỊNH GIÁ','bảng giá tham khảo'))}})}

function installProcurementV4Ui(){
  const grid=$('#orderDialog .order-context .form-grid');
  if(grid&&!$('#orderPaymentMode')){
    const mode=document.createElement('div');mode.className='field';mode.id='orderPaymentModeWrap';mode.innerHTML='<label>Hình thức thanh toán *</label><select id="orderPaymentMode"><option value="DEBT">Công nợ</option><option value="IMMEDIATE">Thanh toán ngay</option></select><div class="hint">Chọn cách xử lý tiền ngay khi tạo đơn.</div>';grid.appendChild(mode);
    const method=document.createElement('div');method.className='field immediate-payment-field hidden';method.innerHTML='<label>Phương thức thanh toán</label><select id="orderImmediateMethod"><option value="BANK">Chuyển khoản</option><option value="CASH">Tiền mặt</option><option value="MOMO">MoMo</option><option value="OTHER">Khác</option></select>';grid.appendChild(method);
    const date=document.createElement('div');date.className='field immediate-payment-field hidden';date.innerHTML='<label>Ngày thanh toán</label><input type="date" id="orderImmediateDate">';grid.appendChild(date);
    const ref=document.createElement('div');ref.className='field immediate-payment-field hidden';ref.innerHTML='<label>Mã tham chiếu</label><input id="orderImmediateReference" placeholder="Mã giao dịch / phiếu chi (nếu có)">';grid.appendChild(ref);
    const notice=document.createElement('div');notice.id='orderPaymentModeNotice';notice.className='notice info span2 hidden';notice.innerHTML='<strong>Thanh toán ngay:</strong> khi lưu đơn, hệ thống sẽ đồng thời ghi nhận thanh toán đủ toàn bộ giá trị đơn. Nếu một bước lỗi, cả đơn và thanh toán đều được hoàn tác.';grid.appendChild(notice);
  }
  const toolbar=$('#sec-orders .toolbar');
  if(toolbar&&!$('#exportOrdersBtn')){const b=document.createElement('button');b.type='button';b.className='btn';b.id='exportOrdersBtn';b.textContent='Tải Excel';toolbar.appendChild(b)}
}
function updateOrderPaymentUi(){
  const editing=!!$('#orderId')?.value,mode=$('#orderPaymentMode')?.value||'DEBT',immediate=!editing&&mode==='IMMEDIATE';
  $('#orderPaymentModeWrap')?.classList.toggle('hidden',editing);
  $$('.immediate-payment-field').forEach(x=>x.classList.toggle('hidden',!immediate));
  $('#orderPaymentModeNotice')?.classList.toggle('hidden',!immediate);
  $('#orderDue')?.closest('.field')?.classList.toggle('hidden',immediate);
  if(immediate){const d=$('#orderDate')?.value||today();if($('#orderImmediateDate'))$('#orderImmediateDate').value=d;if($('#orderDue'))$('#orderDue').value=d}
}
const resetOrderV3=resetOrder;
resetOrder=function(){resetOrderV3();if($('#orderPaymentMode'))$('#orderPaymentMode').value='DEBT';if($('#orderImmediateMethod'))$('#orderImmediateMethod').value='BANK';if($('#orderImmediateReference'))$('#orderImmediateReference').value='';if($('#orderImmediateDate'))$('#orderImmediateDate').value=$('#orderDate').value||today();updateOrderPaymentUi()};
const applySupplierTermsV3=applySupplierTerms;
applySupplierTerms=function(){if($('#orderPaymentMode')?.value==='IMMEDIATE'&&!$('#orderId')?.value){const d=$('#orderDate').value||today();$('#orderDue').value=d;if($('#orderImmediateDate'))$('#orderImmediateDate').value=d;return}applySupplierTermsV3()};
const openOrderStable=openOrder;
openOrder=async function(id=null){await openOrderStable(id);updateOrderPaymentUi();const body=$('#orderDialog .modal-body');if(body){body.scrollTop=0;requestAnimationFrame(()=>body.scrollTop=0)}};

renderOrders=function(){const term=($('#orderSearch').value||'').trim().toLowerCase(),rows=state.orders.filter(o=>!term||`${o.order_no} ${o.supplier_name} ${o.invoice_no||''}`.toLowerCase().includes(term)),body=$('#ordersBody');body.innerHTML='';for(const o of rows){const cancelled=o.status==='CANCELLED',balance=cancelled?0:Number(o.balance_due||0),canEdit=!cancelled,canPay=canEdit&&balance>0;const tr=document.createElement('tr');tr.innerHTML=`<td><strong>${esc(o.order_no)}</strong><div class="hint">v${o.version}</div></td><td>${esc(o.order_date)}</td><td>${esc(o.supplier_name)}</td><td>${esc(o.invoice_no||'')}</td><td class="num"><strong>${money(o.total_amount)}</strong></td><td class="num">${money(o.paid_amount)}</td><td class="num"><strong>${money(balance)}</strong></td><td>${esc(o.due_date||'')}</td><td>${badgePayment(o.payment_status,o.is_overdue)}</td><td><div class="actions">${canEdit?`<button class="btn small" data-edit-order="${o.id}">Sửa</button>`:''}${canPay?`<button class="btn green small" data-pay-order="${o.id}">Thanh toán</button>`:''}<button class="btn small" data-history-order="${o.id}">Lịch sử</button>${canEdit&&Number(o.paid_amount)===0?`<button class="btn danger small" data-cancel-order="${o.id}">Hủy</button>`:''}</div></td>`;body.appendChild(tr)}$('#ordersEmpty').classList.toggle('hidden',rows.length>0);const active=rows.filter(x=>x.status!=='CANCELLED');$('#ordersValueKpi').textContent=money(active.reduce((a,x)=>a+Number(x.total_amount||0),0));$('#ordersDebtKpi').textContent=money(active.reduce((a,x)=>a+Number(x.balance_due||0),0));$('#ordersOpenKpi').textContent=active.filter(x=>Number(x.balance_due)>0).length;$('#ordersOverdueKpi').textContent=active.filter(x=>x.is_overdue).length};

saveOrder=async function(ev){ev.preventDefault();const btn=$('#saveOrderBtn');try{const id=$('#orderId').value,reason=$('#editReason').value.trim();if(id&&!reason)throw new Error('Khi chỉnh sửa đơn, hãy nhập lý do chỉnh sửa.');const items=collectItems(),msgs=validateOrder(items),box=$('#orderValidation');if(msgs.length){box.innerHTML='<strong>Chưa thể lưu:</strong><br>'+msgs.map(esc).join('<br>');box.classList.remove('hidden');throw new Error('Vui lòng kiểm tra các cảnh báo trong đơn nhập.')}box.classList.add('hidden');btn.disabled=true;btn.textContent='Đang lưu…';const order={id:id||null,order_date:$('#orderDate').value,supplier_id:$('#orderSupplier').value,invoice_no:$('#orderInvoice').value.trim(),due_date:$('#orderDue').value||null,notes:$('#orderNotes').value.trim()},mode=!id?($('#orderPaymentMode')?.value||'DEBT'):'DEBT',payment=mode==='IMMEDIATE'?{mode:'IMMEDIATE',payment_date:$('#orderImmediateDate')?.value||$('#orderDate').value,method:$('#orderImmediateMethod')?.value||'BANK',reference:$('#orderImmediateReference')?.value.trim()||null,note:'Thanh toán ngay khi tạo đơn nhập'}:{mode:'DEBT'};const q=await sb.rpc('procurement_save_order_with_payment',{p_order:order,p_items:items,p_reason:reason||null,p_payment:payment});if(q.error)throw q.error;closeDialog('orderDialog');await Promise.all([loadOrders(),loadPayables(),runReport()]);toast(mode==='IMMEDIATE'?`Đã lưu ${q.data?.order_no||'đơn nhập'} và thanh toán đủ ${money(q.data?.total_amount||0)}.`:`Đã lưu ${q.data?.order_no||'đơn nhập'} · ghi nhận công nợ ${money(q.data?.total_amount||0)}.`,'success')}catch(e){showError(e,'saveOrder')}finally{btn.disabled=false;btn.textContent='Lưu đơn nhập'}};

function currentOrderRows(){const term=($('#orderSearch').value||'').trim().toLowerCase();return state.orders.filter(o=>!term||`${o.order_no} ${o.supplier_name} ${o.invoice_no||''}`.toLowerCase().includes(term))}
function exportStatus(o){if(o.status==='CANCELLED')return 'Đã hủy';if(o.payment_status==='PAID')return 'Đã trả';if(o.payment_status==='PARTIAL')return 'Trả một phần';if(o.is_overdue)return 'Quá hạn';return 'Chưa trả'}
async function ensureXlsx(){if(globalThis.XLSX)return globalThis.XLSX;await new Promise((resolve,reject)=>{const old=document.querySelector('script[data-magasin-xlsx]');if(old){old.addEventListener('load',resolve,{once:true});old.addEventListener('error',()=>reject(new Error('Không tải được thư viện Excel.')),{once:true});return}const s=document.createElement('script');s.src='https://cdn.jsdelivr.net/npm/xlsx@0.18.5/dist/xlsx.full.min.js';s.async=true;s.dataset.magasinXlsx='1';s.onload=resolve;s.onerror=()=>reject(new Error('Không tải được thư viện Excel.'));document.head.appendChild(s)});if(!globalThis.XLSX)throw new Error('Thư viện Excel chưa sẵn sàng.');return globalThis.XLSX}
async function exportOrdersExcel(){try{const XLSX=await ensureXlsx(),rows=currentOrderRows().map(o=>({'Mã đơn':o.order_no,'Ngày':o.order_date,'Nhà cung cấp':o.supplier_name,'Hóa đơn':o.invoice_no||'','Tổng tiền':Number(o.total_amount||0),'Đã trả':Number(o.paid_amount||0),'Còn nợ':o.status==='CANCELLED'?0:Number(o.balance_due||0),'Hạn trả':o.due_date||'','Trạng thái':exportStatus(o)}));if(!rows.length)throw new Error('Không có đơn nhập để xuất.');const ws=XLSX.utils.json_to_sheet(rows),wb=XLSX.utils.book_new();ws['!cols']=[{wch:20},{wch:13},{wch:28},{wch:18},{wch:16},{wch:16},{wch:16},{wch:13},{wch:18}];XLSX.utils.book_append_sheet(wb,ws,'Đơn nhập');const from=$('#orderFrom').value||'',to=$('#orderTo').value||'';XLSX.writeFile(wb,`MAGASIN_Don_Nhap_${from}_${to}.xlsx`);toast(`Đã xuất ${rows.length} đơn nhập ra Excel.`,'success')}catch(e){showError(e,'exportOrdersExcel')}}

installProcurementV4Ui();
polishStaticCopy();
$('#nav').addEventListener('click',e=>{const b=e.target.closest('button[data-tab]');if(!b)return;$$('#nav button').forEach(x=>x.classList.remove('active'));b.classList.add('active');$$('.section').forEach(x=>x.classList.remove('active'));$('#sec-'+b.dataset.tab).classList.add('active');if(b.dataset.tab==='payables')loadPayables();if(b.dataset.tab==='reports')runReport()});
document.addEventListener('click',e=>{const c=e.target.closest('[data-close]');if(c)closeDialog(c.dataset.close);const ep=e.target.closest('[data-edit-product]');if(ep)openProduct(ep.dataset.editProduct);const es=e.target.closest('[data-edit-supplier]');if(es)openSupplier(es.dataset.editSupplier);const eo=e.target.closest('[data-edit-order]');if(eo)openOrder(eo.dataset.editOrder);const po=e.target.closest('[data-pay-order]');if(po)openPayment(po.dataset.payOrder);const ho=e.target.closest('[data-history-order]');if(ho)showHistory(ho.dataset.historyOrder);const co=e.target.closest('[data-cancel-order]');if(co)cancelOrder(co.dataset.cancelOrder);if(e.target.matches('.pkg-remove'))e.target.closest('.package-row').remove();if(e.target.matches('.line-remove')){e.target.closest('.line-row').remove();if(!$$('#orderLines .line-row').length)addOrderLine();updateGrandTotal()}});
$('#orderLines').addEventListener('change',e=>{const r=e.target.closest('.line-row');if(!r)return;if(e.target.matches('.line-product'))syncLineDefaults(r);if(e.target.matches('.line-package')){const mode=selectedMode(r),c=ctx(r.querySelector('.line-product').value);delete r.dataset.customFactor;delete r.dataset.customUnit;if(mode.reference&&c){r.querySelector('.line-qty').value='1';r.querySelector('.line-price').value=String(Number(c.source_price||0))}updateLine(r)}else updateLine(r)});
$('#orderLines').addEventListener('input',e=>{const r=e.target.closest('.line-row');if(r)updateLine(r)});
$('#lineProductFilter').addEventListener('input',()=>{$$('#orderLines .line-row').forEach(r=>{const sel=r.querySelector('.line-product'),v=sel.value;sel.innerHTML=productOptions(v);sel.value=v})});
$('#orderSearch').addEventListener('input',renderOrders);$('#productSearch').addEventListener('input',renderProducts);$('#productCategoryFilter').addEventListener('change',renderProducts);$('#productBaseUnit').addEventListener('change',updatePackageUnitLabels);
$('#newProductBtn').onclick=()=>openProduct();$('#newSupplierBtn').onclick=()=>openSupplier();$('#newOrderBtn').onclick=()=>openOrder();$('#addPackageBtn').onclick=()=>{addPackageRow();updatePackageUnitLabels()};$('#addLineBtn').onclick=()=>{addOrderLine();const row=$$('#orderLines .line-row').at(-1);row?.querySelector('.line-product')?.focus()};$('#reloadOrdersBtn').onclick=loadOrders;$('#reloadPayablesBtn').onclick=loadPayables;$('#runReportBtn').onclick=runReport;$('#exportOrdersBtn').onclick=exportOrdersExcel;$('#productForm').addEventListener('submit',saveProduct);$('#supplierForm').addEventListener('submit',saveSupplier);$('#orderForm').addEventListener('submit',saveOrder);$('#paymentForm').addEventListener('submit',savePayment);$('#orderPaymentMode').addEventListener('change',()=>{updateOrderPaymentUi();applySupplierTerms()});$('#orderSupplier').addEventListener('change',applySupplierTerms);$('#orderDate').addEventListener('change',applySupplierTerms);$('#logoutBtn').onclick=async()=>{await sb.auth.signOut();location.replace('/03_PLATFORM/01_AUTH/')};
init();
