'use strict';
const core=globalThis.MAGASIN_CORE,sb=core?.supabase.get();
const $=s=>document.querySelector(s),$$=s=>Array.from(document.querySelectorAll(s));
const money=n=>new Intl.NumberFormat('vi-VN',{style:'currency',currency:'VND',maximumFractionDigits:0}).format(Number(n||0));
const number=n=>new Intl.NumberFormat('vi-VN',{maximumFractionDigits:3}).format(Number(n||0));
const esc=v=>core.security.escapeHtml(v??'');
const today=()=>core.date.dateKey();
const firstOfMonth=()=>today().slice(0,8)+'01';
const catLabel={MATERIAL:'Nguyên liệu',PACKAGING:'Bao bì',GOODS:'Hàng hóa',OTHER:'Vật tư khác'};
const state={profile:null,products:[],packages:[],suppliers:[],orders:[],priceContext:new Map(),priceReferenceAvailable:false};
function toast(m,t='info'){core.ui.toast(m,t)}
function showError(err,context=''){console.error('[PROCUREMENT]',context,err);toast(err?.message||String(err),'error')}
function closeDialog(id){const d=document.getElementById(id);if(d?.open)d.close()}
function addDays(dateStr,n){const [y,m,d]=String(dateStr).slice(0,10).split('-').map(Number),x=new Date(Date.UTC(y,m-1,d));x.setUTCDate(x.getUTCDate()+Number(n||0));return `${x.getUTCFullYear()}-${String(x.getUTCMonth()+1).padStart(2,'0')}-${String(x.getUTCDate()).padStart(2,'0')}`}
function badgePayment(v,overdue){if(v==='CANCELLED')return '<span class="badge danger">Đã hủy</span>';if(v==='PAID')return '<span class="badge ok">Đã trả</span>';if(v==='PARTIAL')return `<span class="badge warn">Trả một phần${overdue?' · quá hạn':''}</span>`;return `<span class="badge ${overdue?'danger':'blue'}">${overdue?'Quá hạn':'Chưa trả'}</span>`}
function ctx(productId){return state.priceContext.get(productId)||null}
function pricePerBase(c){return c&&Number(c.reference_base_quantity)>0?Number(c.source_price||0)/Number(c.reference_base_quantity):0}
function referenceText(c,p){if(!c?.source_price||!c?.reference_base_quantity)return 'Chưa có giá tham chiếu *ĐỊNH GIÁ';const src=`${number(c.source_quantity)} ${c.source_unit||''}`.trim(),base=`${number(c.reference_base_quantity)} ${p?.base_unit||c.base_unit||''}`.trim();return `${money(c.source_price)} / quy cách · ${src}${src!==base?` → ${base}`:''}`}
function sourceModeValue(){return '__REFERENCE__'}
async function init(){try{if(!core||!sb)throw new Error('Không tải được MAGASIN_CORE/Supabase.');state.profile=await core.supabase.requireActive();if(!core.roles.hasRole(state.profile,['OWNER','ACCOUNTANT']))throw new Error('Tài khoản hiện tại chưa được cấp quyền Owner hoặc Kế toán.');$('#userName').textContent=`${state.profile.full_name||state.profile.username} · ${state.profile.role==='ACCOUNTANT'?'Kế toán':'Owner'}`;$('#orderFrom').value=firstOfMonth();$('#orderTo').value=today();$('#reportFrom').value=firstOfMonth();$('#reportTo').value=today();await loadLookups();await Promise.all([loadOrders(),loadPayables()]);await runReport();$('#loading').classList.add('hidden');$('#app').classList.remove('hidden')}catch(e){console.error('[PROCUREMENT_INIT]',e);$('#loading').classList.add('hidden');$('#denied').classList.remove('hidden');$('#deniedText').textContent=e?.message||String(e)}}
async function loadLookups(){let q=await sb.from('procurement_products').select('*').order('name');if(q.error)throw q.error;state.products=q.data||[];q=await sb.from('procurement_product_packages').select('*').order('is_default',{ascending:false}).order('label');if(q.error)throw q.error;state.packages=q.data||[];q=await sb.from('procurement_suppliers').select('*').order('name');if(q.error)throw q.error;state.suppliers=q.data||[];state.priceContext=new Map();const pc=await sb.from('v_procurement_product_price_context').select('*');if(!pc.error){state.priceReferenceAvailable=true;(pc.data||[]).forEach(x=>state.priceContext.set(x.product_id,x))}else{state.priceReferenceAvailable=false;console.warn('[PROCUREMENT_REFERENCE_FALLBACK]',pc.error.message)}renderProducts();renderSuppliers();fillSupplierSelect();updateReferenceCoverage()}
function updateReferenceCoverage(){const covered=state.products.filter(p=>ctx(p.id)?.source_price!=null).length;const el=$('#referenceCoverage');if(!el)return;el.className='notice '+(state.priceReferenceAvailable?'info':'warn');el.innerHTML=state.priceReferenceAvailable?`*ĐỊNH GIÁ: <strong>${covered}/${state.products.length}</strong> hàng hóa có giá/quy cách tham chiếu. Mặt hàng không có nguồn sẽ để kế toán nhập thủ công.`:'Bảng giá tham chiếu chưa sẵn sàng; vẫn có thể nhập đơn thủ công.'}
function filteredProducts(){const term=($('#productSearch')?.value||'').trim().toLowerCase(),cat=$('#productCategoryFilter')?.value||'';return state.products.filter(p=>(!cat||p.category===cat)&&(!term||`${p.code} ${p.name}`.toLowerCase().includes(term)))}
function renderProducts(){const body=$('#productsBody');if(!body)return;body.innerHTML='';for(const p of filteredProducts()){const packs=state.packages.filter(x=>x.product_id===p.id&&x.status==='ACTIVE'),c=ctx(p.id);const ref=c?.source_price!=null?`<strong>${money(c.source_price)}</strong><div class="hint">${esc(number(c.source_quantity))} ${esc(c.source_unit||'')} · ${esc(number(c.reference_base_quantity))} ${esc(p.base_unit)} chuẩn</div>`:'<span class="badge warn">Chưa có nguồn</span>';const tr=document.createElement('tr');tr.innerHTML=`<td><strong>${esc(p.code)}</strong></td><td>${esc(p.name)}</td><td>${esc(catLabel[p.category]||p.category)}</td><td><span class="badge ${p.base_unit==='cái'?'':'blue'}">${esc(p.base_unit)}</span></td><td>${ref}</td><td>${packs.length?packs.map(x=>`${esc(x.label)} = ${number(x.base_qty_per_unit)} ${esc(p.base_unit)}`).join('<br>'):'<span class="muted">Không có quy cách riêng</span>'}</td><td>${p.status==='ACTIVE'?'<span class="badge ok">Đang dùng</span>':'<span class="badge">Ngưng dùng</span>'}</td><td><button class="btn small" data-edit-product="${p.id}">Sửa</button></td>`;body.appendChild(tr)}$('#productsEmpty').classList.toggle('hidden',body.children.length>0)}
function renderSuppliers(){const body=$('#suppliersBody');body.innerHTML='';for(const s of state.suppliers){const tr=document.createElement('tr');tr.innerHTML=`<td><strong>${esc(s.code)}</strong></td><td>${esc(s.name)}</td><td>${esc(s.contact_name||'')}</td><td>${esc(s.phone||'')}</td><td>${number(s.payment_terms_days)} ngày</td><td>${s.status==='ACTIVE'?'<span class="badge ok">Đang dùng</span>':'<span class="badge">Ngưng dùng</span>'}</td><td><button class="btn small" data-edit-supplier="${s.id}">Sửa</button></td>`;body.appendChild(tr)}$('#suppliersEmpty').classList.toggle('hidden',state.suppliers.length>0)}
function fillSupplierSelect(){const sel=$('#orderSupplier');sel.innerHTML='<option value="">-- Chọn nhà cung cấp --</option>'+state.suppliers.filter(s=>s.status==='ACTIVE').map(s=>`<option value="${s.id}">${esc(s.name)} (${esc(s.code)})</option>`).join('')}
async function loadOrders(){const from=$('#orderFrom').value||'2000-01-01',to=$('#orderTo').value||'2999-12-31',q=await sb.from('v_procurement_order_summary').select('*').gte('order_date',from).lte('order_date',to).order('order_date',{ascending:false}).order('created_at',{ascending:false});if(q.error)return showError(q.error,'loadOrders');state.orders=q.data||[];renderOrders()}
function renderOrders(){const term=($('#orderSearch').value||'').trim().toLowerCase(),rows=state.orders.filter(o=>!term||`${o.order_no} ${o.supplier_name} ${o.invoice_no||''}`.toLowerCase().includes(term)),body=$('#ordersBody');body.innerHTML='';for(const o of rows){const tr=document.createElement('tr'),canEdit=o.status!=='CANCELLED',canPay=canEdit&&Number(o.balance_due)>0;tr.innerHTML=`<td><strong>${esc(o.order_no)}</strong><div class="hint">v${o.version}</div></td><td>${esc(o.order_date)}</td><td>${esc(o.supplier_name)}</td><td>${esc(o.invoice_no||'')}</td><td class="num"><strong>${money(o.total_amount)}</strong></td><td class="num">${money(o.paid_amount)}</td><td class="num"><strong>${money(o.balance_due)}</strong></td><td>${esc(o.due_date||'')}</td><td>${badgePayment(o.payment_status,o.is_overdue)}</td><td><div class="actions">${canEdit?`<button class="btn small" data-edit-order="${o.id}">Sửa</button>`:''}${canPay?`<button class="btn green small" data-pay-order="${o.id}">Thanh toán</button>`:''}<button class="btn small" data-history-order="${o.id}">Lịch sử</button>${canEdit&&Number(o.paid_amount)===0?`<button class="btn danger small" data-cancel-order="${o.id}">Hủy</button>`:''}</div></td>`;body.appendChild(tr)}$('#ordersEmpty').classList.toggle('hidden',rows.length>0);$('#ordersValueKpi').textContent=money(rows.reduce((a,x)=>a+Number(x.total_amount||0),0));$('#ordersDebtKpi').textContent=money(rows.reduce((a,x)=>a+Number(x.balance_due||0),0));$('#ordersOpenKpi').textContent=rows.filter(x=>Number(x.balance_due)>0&&x.status!=='CANCELLED').length;$('#ordersOverdueKpi').textContent=rows.filter(x=>x.is_overdue).length}
async function loadPayables(){const [p,o]=await Promise.all([sb.from('v_procurement_supplier_payables').select('*').order('balance_due',{ascending:false}),sb.from('v_procurement_order_summary').select('id,balance_due,status,is_overdue').neq('status','CANCELLED')]);if(p.error)return showError(p.error,'loadPayables');if(o.error)return showError(o.error,'loadPayables orders');const rows=p.data||[],$b=$('#payablesBody');$b.innerHTML='';for(const r of rows.filter(x=>Number(x.total_purchases)>0||Number(x.balance_due)>0)){const tr=document.createElement('tr');tr.innerHTML=`<td><strong>${esc(r.supplier_name)}</strong><div class="hint">${esc(r.supplier_code)}</div></td><td class="num">${money(r.total_purchases)}</td><td class="num">${money(r.total_paid)}</td><td class="num"><strong>${money(r.balance_due)}</strong></td><td class="num">${Number(r.overdue_balance)>0?`<span class="badge danger">${money(r.overdue_balance)}</span>`:money(0)}</td><td>${esc(r.oldest_due_date||'')}</td>`;$b.appendChild(tr)}$('#payableTotal').textContent=money(rows.reduce((a,r)=>a+Number(r.balance_due||0),0));$('#overdueTotal').textContent=money(rows.reduce((a,r)=>a+Number(r.overdue_balance||0),0));$('#supplierDebtCount').textContent=rows.filter(r=>Number(r.balance_due)>0).length;$('#openDebtOrders').textContent=(o.data||[]).filter(r=>Number(r.balance_due)>0).length}
function updatePackageUnitLabels(){const u=$('#productBaseUnit').value||'';$$('#packageRows .pkg-base-unit').forEach(x=>x.textContent=u)}
async function openProduct(id=null){try{const p=id?state.products.find(x=>x.id===id):null;$('#productTitle').textContent=p?'Sửa hàng hóa':'Thêm hàng hóa';$('#productId').value=p?.id||'';$('#productCode').value=p?.code||'';$('#productName').value=p?.name||'';$('#productCategory').value=p?.category||'MATERIAL';$('#productBaseUnit').value=p?.base_unit||'g';$('#productStatus').value=p?.status||'ACTIVE';$('#productNotes').value=p?.notes||'';$('#packageRows').innerHTML='';const packs=p?state.packages.filter(x=>x.product_id===p.id&&x.status==='ACTIVE'):[];packs.forEach(addPackageRow);if(!packs.length)addPackageRow();let locked=false;if(p){const c=await sb.from('procurement_purchase_order_items').select('id',{count:'exact',head:true}).eq('product_id',p.id);if(c.error)throw c.error;locked=Number(c.count||0)>0}$('#productBaseUnit').disabled=locked;$('#unitLockNotice').classList.toggle('hidden',!locked);$('#productUnitHint').textContent=locked?'Đã có giao dịch: đơn vị tồn chuẩn không được thay đổi.':'Ưu tiên g/ml theo *ĐỊNH GIÁ; chỉ dùng cái cho hàng đếm chiếc.';updatePackageUnitLabels();$('#productDialog').showModal()}catch(e){showError(e,'openProduct')}}
function addPackageRow(x={}){const d=document.createElement('div');d.className='package-row';d.dataset.id=x.id||'';d.innerHTML=`<div class="field"><label>Tên quy cách</label><input class="pkg-label" value="${esc(x.label||'')}" placeholder="VD: Bao 30kg / Thùng 24 chai"></div><div class="field"><label>ĐVT mua</label><input class="pkg-unit" value="${esc(x.purchase_unit||'')}" placeholder="bao / thùng / chai"></div><div class="field"><label>Quy đổi</label><div class="conversion-box"><span>1 ĐVT mua =</span><input class="pkg-factor" type="number" min="0.000001" step="any" value="${x.base_qty_per_unit||''}" placeholder="VD: 30000"><span class="pkg-base-unit">${esc($('#productBaseUnit').value||'')}</span></div></div><button type="button" class="btn danger small pkg-remove">${x.id?'Ngưng':'Bỏ'}</button>`;$('#packageRows').appendChild(d)}
async function saveProduct(ev){ev.preventDefault();try{const id=$('#productId').value,session=(await core.supabase.getSession()).user,current=id?state.products.find(x=>x.id===id):null,payload={code:$('#productCode').value.trim()||null,name:$('#productName').value.trim(),category:$('#productCategory').value,base_unit:$('#productBaseUnit').disabled&&current?current.base_unit:$('#productBaseUnit').value,status:$('#productStatus').value,notes:$('#productNotes').value.trim()||null,updated_by:session.id};if(!payload.name)throw new Error('Hãy nhập tên hàng hóa.');if(payload.category==='MATERIAL'&&payload.base_unit==='cái'&&!/flan/i.test(payload.name))throw new Error('Nguyên liệu định lượng phải quy về g hoặc ml. Nếu đây là hàng đếm chiếc đặc biệt, hãy ghi rõ và dùng nhóm phù hợp.');let productId=id;if(id){const q=await sb.from('procurement_products').update(payload).eq('id',id).select('id').single();if(q.error)throw q.error}else{payload.created_by=session.id;const q=await sb.from('procurement_products').insert(payload).select('id').single();if(q.error)throw q.error;productId=q.data.id}const rows=$$('#packageRows .package-row'),keep=[];for(const r of rows){const label=r.querySelector('.pkg-label').value.trim(),unit=r.querySelector('.pkg-unit').value.trim(),factor=Number(r.querySelector('.pkg-factor').value);if(!label&&!unit&&!factor)continue;if(!label||!unit||!(factor>0))throw new Error('Mỗi quy cách phải có tên, đơn vị mua và số quy đổi lớn hơn 0.');const pp={product_id:productId,label,purchase_unit:unit,base_qty_per_unit:factor,status:'ACTIVE',updated_by:session.id};if(r.dataset.id){keep.push(r.dataset.id);const q=await sb.from('procurement_product_packages').update(pp).eq('id',r.dataset.id);if(q.error)throw q.error}else{pp.created_by=session.id;const q=await sb.from('procurement_product_packages').insert(pp).select('id').single();if(q.error)throw q.error;keep.push(q.data.id)}}if(id){const old=state.packages.filter(x=>x.product_id===id&&x.status==='ACTIVE'&&!keep.includes(x.id)).map(x=>x.id);if(old.length){const q=await sb.from('procurement_product_packages').update({status:'INACTIVE',updated_by:session.id}).in('id',old);if(q.error)throw q.error}}closeDialog('productDialog');await loadLookups();toast('Đã lưu hàng hóa.','success')}catch(e){showError(e,'saveProduct')}}
function openSupplier(id=null){const s=id?state.suppliers.find(x=>x.id===id):null;$('#supplierTitle').textContent=s?'Sửa nhà cung cấp':'Thêm nhà cung cấp';$('#supplierId').value=s?.id||'';$('#supplierCode').value=s?.code||'';$('#supplierName').value=s?.name||'';$('#supplierContact').value=s?.contact_name||'';$('#supplierPhone').value=s?.phone||'';$('#supplierEmail').value=s?.email||'';$('#supplierTax').value=s?.tax_code||'';$('#supplierTerms').value=s?.payment_terms_days||0;$('#supplierStatus').value=s?.status||'ACTIVE';$('#supplierNotes').value=s?.notes||'';$('#supplierDialog').showModal()}
async function saveSupplier(ev){ev.preventDefault();try{const id=$('#supplierId').value,session=(await core.supabase.getSession()).user,payload={code:$('#supplierCode').value.trim()||null,name:$('#supplierName').value.trim(),contact_name:$('#supplierContact').value.trim()||null,phone:$('#supplierPhone').value.trim()||null,email:$('#supplierEmail').value.trim()||null,tax_code:$('#supplierTax').value.trim()||null,payment_terms_days:Number($('#supplierTerms').value||0),status:$('#supplierStatus').value,notes:$('#supplierNotes').value.trim()||null,updated_by:session.id};if(!payload.name)throw new Error('Hãy nhập tên nhà cung cấp.');if(id){const q=await sb.from('procurement_suppliers').update(payload).eq('id',id);if(q.error)throw q.error}else{payload.created_by=session.id;const q=await sb.from('procurement_suppliers').insert(payload);if(q.error)throw q.error}closeDialog('supplierDialog');await loadLookups();toast('Đã lưu nhà cung cấp.','success')}catch(e){showError(e,'saveSupplier')}}
