(()=>{'use strict';
const C=globalThis.MAGASIN_CORE;if(!C)return;
const host=()=>document.getElementById('employeeApp');
const doc=()=>host()?.contentDocument||null;
const esc=C.security.escapeHtml,hm=C.time.time5,kind=C.time.shiftKind,fmt=C.date.formatDate,add=C.date.addDays,mon=C.date.monday;
const DAYS=['Thứ Hai','Thứ Ba','Thứ Tư','Thứ Năm','Thứ Sáu','Thứ Bảy','Chủ Nhật'];
let state={rows:[],week:mon(),ready:false};
const css=`<style id="employee-schedule-engine-v1-css">.employee-schedule-engine .days{display:grid;grid-template-columns:repeat(7,minmax(0,1fr));gap:9px}.employee-schedule-engine .shift.morning-yellow{background:#fff8dc!important;border:1px solid #ead97c}.employee-schedule-engine .shift.afternoon-red{background:#fff0f0!important;border:1px solid #efb7b7}.employee-schedule-engine .shift.evening-cyan{background:#edfafa!important;border:1px solid #a6dede}.employee-schedule-engine .dow{font-weight:900}.employee-schedule-engine .date{font-size:12px;color:var(--muted);margin-top:3px}.employee-schedule-engine .today-tag{display:inline-block;margin-top:6px}</style>`;
function ensureCss(d){if(d&&!d.getElementById('employee-schedule-engine-v1-css'))d.head.insertAdjacentHTML('beforeend',css)}
function identity(d){const p=globalThis.MAGASIN_EMPLOYEE?.profile;if(!p||!d)return;const n=p.full_name||p.username||'Nhân viên';const r=C.roles.label[String(p.role||'STAFF').toUpperCase()]||String(p.role||'STAFF');d.querySelector('.header-user-text strong')?.replaceChildren(d.createTextNode(n));d.querySelector('.header-user-text span')?.replaceChildren(d.createTextNode(r));const a=d.querySelector('.header-avatar');if(a)a.textContent=n.charAt(0).toUpperCase()}
function paint(d){if(!d)return;ensureCss(d);identity(d);const days=d.querySelector('#view-schedule .schedule-main-panel .days');if(!days)return;days.replaceChildren(...C.date.weekDays(state.week).map((date,i)=>{const el=d.createElement('div');el.className='day'+(date===C.date.dateKey()?' today':'');el.innerHTML=`<div class="dow">${DAYS[i]}</div><div class="date">${fmt(date)}</div>`+(date===C.date.dateKey()?'<span class="today-tag">HÔM NAY</span>':'');const rows=state.rows.filter(r=>String(r.work_date).slice(0,10)===date).sort((a,b)=>C.time.minutes(a.start_time)-C.time.minutes(b.start_time)||C.time.minutes(a.end_time)-C.time.minutes(b.end_time));if(!rows.length){el.insertAdjacentHTML('beforeend','<div class="muted" style="margin-top:18px">Không có ca</div>');return el}for(const r of rows){const sh=d.createElement('div');const k=kind(r.start_time);sh.className=`shift ${k==='morning'?'morning-yellow':k==='afternoon'?'afternoon-red':'evening-cyan'}`;sh.innerHTML=`<b>${esc(hm(r.start_time))}–${esc(hm(r.end_time))}</b><div class="store">${esc(r.store_code||r.store_name||'Cửa hàng')}</div>`;el.appendChild(sh)}return el}));const pill=d.querySelector('#view-schedule .schedule-main-panel .pill');if(pill)pill.textContent=`Tuần ${fmt(state.week)}–${fmt(add(state.week,6))}`}
async function refresh(){const d=doc();if(!d)return;state.week=state.week||mon();C.ui.setLoading(d.body,true);try{const q=await C.supabase.rpc('list_my_approved_schedules_v2',{p_week_start:state.week});if(q.error)throw q.error;state.rows=Array.isArray(q.data)?q.data:[];paint(d);state.ready=true;globalThis.MAGASIN_EMPLOYEE?.events?.emit?.('schedule-loaded',{rows:state.rows,week:state.week})}catch(e){C.ui.toast(`Không tải được lịch làm: ${e.message||e}`,'error')}finally{C.ui.setLoading(d.body,false)}}
function bind(d){if(!d||d.body.dataset.employeeScheduleEngine==='1')return;d.body.dataset.employeeScheduleEngine='1';d.addEventListener('click',e=>{const a=e.target.closest?.('a,[data-view]');const v=a?.dataset?.view;if(v!=='schedule')return;setTimeout(refresh,0)},true)}
function init(){const f=host();if(!f||f.dataset.scheduleEngine==='1')return;f.dataset.scheduleEngine='1';f.addEventListener('load',()=>{const d=doc();if(!d)return;bind(d);refresh()},{once:false});if(f.contentDocument){bind(f.contentDocument);refresh()}}
globalThis.MAGASIN_EMPLOYEE=globalThis.MAGASIN_EMPLOYEE||{};globalThis.MAGASIN_EMPLOYEE.schedule={refresh,getRows:()=>state.rows.slice(),getWeek:()=>state.week,getTodayRows:()=>state.rows.filter(r=>String(r.work_date).slice(0,10)===C.date.dateKey())};if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
})();