(()=>{'use strict';
const C=globalThis.MAGASIN_CORE;if(!C)return;
const host=()=>document.getElementById('employeeApp');
const doc=()=>host()?.contentDocument||null;
const esc=C.security.escapeHtml,hm=C.time.time5,kind=C.time.shiftKind,fmt=C.date.formatDate,add=C.date.addDays,mon=C.date.monday;
const DAYS=['Thứ Hai','Thứ Ba','Thứ Tư','Thứ Năm','Thứ Sáu','Thứ Bảy','Chủ Nhật'];
let state={rows:[],week:mon(),ready:false,error:null,loading:false};let requestSeq=0,pending=null;
const css=`<style id="employee-schedule-engine-v1-css">.employee-schedule-engine .days{display:grid;grid-template-columns:repeat(7,minmax(0,1fr));gap:9px}.employee-schedule-engine .shift.morning-yellow{background:#fff8dc!important;border:1px solid #ead97c}.employee-schedule-engine .shift.afternoon-red{background:#fff0f0!important;border:1px solid #efb7b7}.employee-schedule-engine .shift.evening-cyan{background:#edfafa!important;border:1px solid #a6dede}.employee-schedule-engine .dow{font-weight:900}.employee-schedule-engine .date{font-size:12px;color:var(--muted);margin-top:3px}.employee-schedule-engine .today-tag{display:inline-block;margin-top:6px}.employee-schedule-engine .schedule-week-nav{display:flex;gap:6px;flex-wrap:wrap;align-items:center;margin:10px 0 12px}.employee-schedule-engine .schedule-week-nav button{border:1px solid #dbe4ef;border-radius:9px;background:#fff;padding:7px 10px;font:inherit;font-weight:700;cursor:pointer}.employee-schedule-engine .schedule-week-nav button[data-schedule-week="today"]{background:#eef5ff;color:#235dba}</style>`;
function ensureCss(d){if(d&&!d.getElementById('employee-schedule-engine-v1-css'))d.head.insertAdjacentHTML('beforeend',css)}
function ensureWeekNav(d){const panel=d?.querySelector('#view-schedule .schedule-main-panel');if(!panel)return;panel.classList.add('employee-schedule-engine');if(panel.querySelector('[data-schedule-week-nav]'))return;const nav=d.createElement('div');nav.className='schedule-week-nav';nav.dataset.scheduleWeekNav='1';nav.innerHTML='<button type="button" data-schedule-week="prev">← Tuần trước</button><button type="button" data-schedule-week="today">Tuần này</button><button type="button" data-schedule-week="next">Tuần sau →</button>';const days=panel.querySelector('.days');if(days)panel.insertBefore(nav,days);else panel.appendChild(nav)}
function identity(d){const p=globalThis.MAGASIN_EMPLOYEE?.profile;if(!p||!d)return;const n=p.full_name||p.username||'Nhân viên';const r=C.roles.label[String(p.role||'STAFF').toUpperCase()]||String(p.role||'STAFF');d.querySelector('.header-user-text strong')?.replaceChildren(d.createTextNode(n));d.querySelector('.header-user-text span')?.replaceChildren(d.createTextNode(r));const a=d.querySelector('.header-avatar');if(a)a.textContent=n.charAt(0).toUpperCase()}
function paint(d){if(!d||!d.body)return;ensureCss(d);ensureWeekNav(d);identity(d);const days=d.querySelector('#view-schedule .schedule-main-panel .days');if(!days)return;const pill=d.querySelector('#view-schedule .schedule-main-panel .pill');const label=`Tuần ${fmt(state.week)}–${fmt(add(state.week,6))}`;if(state.loading){days.innerHTML=`<div data-schedule-loading="1" class="empty" style="grid-column:1/-1">Đang tải lịch ${esc(label.toLowerCase())}…</div>`;if(pill)pill.textContent='Đang tải · '+label;return}if(state.error){days.innerHTML=`<div data-schedule-error="1" class="empty" style="grid-column:1/-1;border-color:#efb7b7;background:#fff0f0;color:#9a3838"><b>Không tải được lịch làm</b><div style="margin-top:5px">${esc(state.error)}</div></div>`;if(pill)pill.textContent='Lỗi tải · '+label;return}days.replaceChildren(...C.date.weekDays(state.week).map((date,i)=>{const el=d.createElement('div');el.className='day'+(date===C.date.dateKey()?' today':'');el.innerHTML=`<div class="dow">${DAYS[i]}</div><div class="date">${fmt(date)}</div>`+(date===C.date.dateKey()?'<span class="today-tag">HÔM NAY</span>':'');const rows=state.rows.filter(r=>String(r.work_date).slice(0,10)===date).sort((a,b)=>C.time.minutes(a.start_time)-C.time.minutes(b.start_time)||C.time.minutes(a.end_time)-C.time.minutes(b.end_time));if(!rows.length){el.insertAdjacentHTML('beforeend','<div class="muted" style="margin-top:18px">Không có ca</div>');return el}for(const r of rows){const sh=d.createElement('div');const k=kind(r.start_time);sh.className=`shift ${k==='morning'?'morning-yellow':k==='afternoon'?'afternoon-red':'evening-cyan'}`;sh.innerHTML=`<b>${esc(hm(r.start_time))}–${esc(hm(r.end_time))}</b><div class="store">${esc(r.store_code||r.store_name||'Cửa hàng')}</div>`;el.appendChild(sh)}return el}));if(pill)pill.textContent=label}
async function refresh(){const d=doc();if(!d||!d.body)return;const requestedWeek=state.week||mon();state.week=requestedWeek;if(pending?.week===requestedWeek)return pending.promise;const seq=++requestSeq;state.loading=true;state.error=null;state.rows=[];paint(d);C.ui.setLoading(d.body,true);const run=(async()=>{try{const q=await C.supabase.rpc('list_my_approved_schedules_v2',{p_week_start:requestedWeek});if(seq!==requestSeq||requestedWeek!==state.week)return;if(q.error)throw q.error;state.rows=Array.isArray(q.data)?q.data:[];state.error=null;state.loading=false;paint(d);state.ready=true;globalThis.MAGASIN_EMPLOYEE?.events?.emit?.('schedule-loaded',{rows:state.rows,week:requestedWeek})}catch(e){if(seq!==requestSeq||requestedWeek!==state.week)return;state.rows=[];state.error=e?.message||e?.code||String(e);state.loading=false;paint(d);C.ui.toast(`Không tải được lịch làm: ${state.error}`,'error')}finally{if(seq===requestSeq&&doc()===d&&d.body)C.ui.setLoading(d.body,false)}})();pending={week:requestedWeek,promise:run};try{return await run}finally{if(pending?.promise===run)pending=null}}
function bind(d){if(!d||!d.body||d.body.dataset.employeeScheduleEngine==='1')return;d.body.dataset.employeeScheduleEngine='1';d.addEventListener('click',e=>{const weekButton=e.target.closest?.('[data-schedule-week]');if(weekButton){const action=weekButton.dataset.scheduleWeek;state.week=action==='prev'?add(state.week,-7):action==='next'?add(state.week,7):mon();setTimeout(()=>{void refresh()},0);return}const a=e.target.closest?.('a,[data-view]');const v=a?.dataset?.view;if(v!=='schedule')return;setTimeout(()=>{void refresh()},0)},true)}
function init(){const f=host();if(!f||f.dataset.scheduleEngine==='1')return;f.dataset.scheduleEngine='1';f.addEventListener('load',()=>{const d=doc();if(!d?.body)return;bind(d);void refresh()},{once:false});if(f.contentDocument?.body){bind(f.contentDocument);void refresh()}}
globalThis.MAGASIN_EMPLOYEE=globalThis.MAGASIN_EMPLOYEE||{};globalThis.MAGASIN_EMPLOYEE.schedule={refresh,getRows:()=>state.rows.slice(),getWeek:()=>state.week,getTodayRows:()=>state.rows.filter(r=>String(r.work_date).slice(0,10)===C.date.dateKey())};if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
})();